spring:
  kafka:
    bootstrap-servers: 10.13.14.222:9092,10.13.14.222:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: canal
    password: canal
    virtual-host: canal
    template:
      exchange: canal_exchange

canal:
  server: ${spring.rabbitmq.host}
  destination: sample-data
  async: true
  server-mode: rabbit_mq
  # kafka:
  #  groupId: sample-test-group
  rabbit-mq:
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: ${spring.rabbitmq.virtual-host}

